application: pestermp
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon
- url: /login.py
  script: pesterMP.py
- url: /callback.py
  script: pesterMP.py
- url: /post.py
  script: pesterMP.py
- url: /progress.py
  script: pesterMP.py
- url: /send.py
  script: pesterMP.py
- url: /*
  script: pesterMP.py
